- import_playbook: setup-k8s.yml
- import_playbook: install-k8s-tools.yml
- import_playbook: init-master.yml

- name: Install Calico CNI
  hosts: control_plane
  become: no

  tasks:
    - name: Apply Calico networking
      command: kubectl --kubeconfig=/home/anand/.kube/config apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/calico.yaml

- name: Generate Kubernetes join command
  hosts: control_plane
  become: yes

  tasks:
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Store join command
      set_fact:
        kube_join_command: "{{ join_cmd.stdout }}"

- name: Join worker nodes
  hosts: workers
  become: yes

  tasks:
    - name: Join worker to Kubernetes cluster
      command: "{{ hostvars['control_plane'].kube_join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf

- name: Deploy YOLO app
  hosts: control_plane
  become: no

  tasks:
    - name: Copy deployment file
      copy:
        src: yolo-deployment.yaml
        dest: /home/anand/yolo-deployment.yaml

    - name: Copy service file
      copy:
        src: yolo-service.yaml
        dest: /home/anand/yolo-service.yaml

    - name: Apply deployment
      command: kubectl --kubeconfig=/home/anand/.kube/config apply -f /home/anand/yolo-deployment.yaml

    - name: Apply service
      command: kubectl --kubeconfig=/home/anand/.kube/config apply -f /home/anand/yolo-service.yaml